run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - bodyclose
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/takutakahashi/kommon

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0