name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v -race ./... -short

    - name: Build goose image for integration tests
      run: docker build -t goose:latest -f Dockerfile.goose .

    - name: Run integration tests
      run: go test -v ./... -run TestDocker

    - name: Run linter
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m